- .solcover.js
- .travis.yml
- package.json
Update travis,yml and add solcover.js
> Dmytropodelnik

- contracts/ERC20Token.sol
- contracts/LockedControl.sol
- contracts/LockedDealV2.sol
- contracts/LockedPoolz.sol
- contracts/LockedPoolzData.sol
- contracts/Manageable.sol
- contracts/Token.sol
- migrations/2_deploy_contracts.js
- package.json
- test/1_TrustSwap.js
- test/2_CreatePool.js
- test/3_FailCreatePool.js
- test/4_Access.js
- test/5_Managable.js
- test/6_Events.js
- test/7_Withdraw.js
- truffle-config.js
> updated to version 8

- contracts/LockedControl.sol
- contracts/Manageable.sol
- test/5_Managable.js
using fee helper with locked-deal-v2
> Fee helper

- contracts/LockedControl.sol
- contracts/LockedDealEvents.sol
- contracts/LockedDealModifiers.sol
- contracts/LockedDealV2.sol
- contracts/LockedPoolz.sol
- contracts/PoolzManageable.sol
> split the contract into smaller files

- contracts/LockedDealModifiers.sol
> remove variable

- contracts/LockedDealModifiers.sol
- contracts/LockedManageable.sol
- test/5_Managable.js
> removed MinDuration variable

- README.md
> added explanation of admin settings

- README.md
> license label added

- contracts/LockedControl.sol
- contracts/LockedPoolz.sol
- contracts/LockedPoolzData.sol
- package.json
> added array library

- contracts/LockedDealV2.sol
> fix boolean expression

- contracts/LockedControl.sol
- contracts/LockedDealEvents.sol
- test/1_TrustSwap.js
- test/2_CreatePool.js
- test/3_FailCreatePool.js
- test/4_Access.js
- test/5_Managable.js
- test/6_Events.js
- test/7_Withdraw.js
> change transferPoolOwnership function to PoolTransfer

- contracts/LockedControl.sol
- test/7_Withdraw.js
> fix overflow bug

- contracts/LockedControl.sol
- contracts/LockedCreation.sol
> splitting of creation logic

- test/2_CreatePool.js
- test/3_FailCreatePool.js
- test/4_Access.js
> added failure tests

- contracts/LockedControl.sol
> Added notZeroAddress modifier to SplitPoolAmount and SplitPoolAmountFrom functions

- contracts/LockedPoolzData.sol
- test/1_TrustSwap.js
- test/2_CreatePool.js
- test/4_Access.js
- test/7_Withdraw.js
> removed msg.sender calls from view functions

- contracts/LockedControl.sol
- contracts/LockedDealModifiers.sol
- contracts/LockedPoolz.sol
- package.json
- test/4_Access.js
> updated isLocked modifier

- contracts/LockedControl.sol
- contracts/LockedPoolz.sol
just small  PoolTransfer refactor
> Pool transfer

- contracts/LockedControl.sol
- test/4_Access.js
> removed require(pool.FinishTime > block.timestamp) from PoolTransfer

- contracts/LockedControl.sol
- test/7_Withdraw.js
> added isLocked modifier, now only when the debit amount is zero we can use the PoolTransfer function

- .travis.yml
- contracts/LockedDealEvents.sol
> events are indexed

- contracts/LockedDealEvents.sol
- contracts/LockedDealV2.sol
> changed TokenWithdrawn event

- contracts/LockedManageable.sol
> updated isTokenWhiteListed function

- contracts/LockedPoolzData.sol
- test/2_CreatePool.js
> added two new view functions with tests

- contracts/LockedCreation.sol
- contracts/LockedDealModifiers.sol
- test/3_FailCreatePool.js
- test/4_Access.js
> added CliffTime length check

- contracts/LockedControl.sol
- test/4_Access.js
> removed notZeroValue modifier from ApproveAllowance function
